services:
  web:
    image: portfolio-proj-devops:v1
    command: /bin/bash -c sleep 1000000
    volumes:
      - ./proj/:/usr/src/app/
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data:
    name: postgres_data
